spring:
  datasource:
    username: root
    password: W2kindred
    url: jdbc:mysql://localhost:3306/mybatis?useSSL=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

    # springboot\u9ED8\u8BA4\u662F\u4E0D\u914D\u7F6E\u5176\u4ED6\u5C5E\u6027\u7684\uFF0C\u9700\u8981\u81EA\u5DF1\u7ED1\u5B9A
    #   \u6570\u636E\u6E90\u5176\u4ED6\u914D\u7F6E
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    #   \u914D\u7F6E\u76D1\u63A7\u7EDF\u8BA1\u62E6\u622A\u7684filters\uFF0Cstat:\u76D1\u63A7\u7EDF\u8BA1\uFF0C\u53BB\u6389\u540E\u76D1\u63A7\u754C\u9762sql\u65E0\u6CD5\u7EDF\u8BA1\uFF0C\uFF1Blog4j\u65E5\u5FD7\u8BB0\u5F55\uFF1B'wall'\u7528\u4E8E\u9632\u706B\u5899\uFF0C\u9632\u5FA1sql\u6CE8\u5165
    filters: stat,wall,log4j
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
  thymeleaf:
    cache: false

mybatis:
  type-aliases-package: com.mildlamb.pojo
  mapper-locations: mapper/*.xml

