spring:
  datasource:
    username: root
    password: W2kindred
    url: jdbc:mysql://localhost:3306/mybatis?useSSL=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
# \u6574\u5408mybatis
mybatis:
  type-aliases-package: com.mildlamb.pojo
  mapper-locations: classpath:mybatis/mapper/*.xml