server:
  port: 8081

# 服务应用名字
dubbo:
  application:
    name: Server Of Provider
# 注册中心地址
  registry:
    address: zookeeper://127.0.0.1:2181
# 哪些服务要被注册
  scan:
    base-packages: com.mildlamb.server